<?php
namespace app\controllers;

class LoginController extends BaseControler
{
    public function index()
    {
        session_start();
        if ($_SESSION['authorized']){
            header("Location: /admin");
        }

        parent::index(); // TODO: Change the autogenerated stub
    }

    protected function render($data){
        include TEMPLATE_DIR . "/login.php";
    }
}